import type { Patient } from './supabase'

export const MOCK_PATIENTS: Patient[] = [
  {
    // ── Identity ──
    ptnum: 'PT-00142', label: 1, scc: 148, gender: 'm',
    first_name: 'Robert', last_name: 'Hargrove', middle_name: 'James',
    date_of_birth: '1957-03-14', age: 67,
    administrative_sex: 'Male', birth_sex: 'Male', gender_identity: 'Male',
    preferred_language: 'English',
    race: 'White', ethnicity: 'Nonhispanic', tribal_affiliation: null,
    marital: 'Married',
    address_line: '142 Elmwood Ave', city: 'Boston', state: 'Massachusetts', zip_code: '02101',
    phone: '(617) 555-0142', email: 'r.hargrove@email.com',
    // ── Vitals ──
    systolic_bp: 152, diastolic_bp: 94, heart_rate: 82,
    respiratory_rate: 18, temperature_c: 37.1, oxygen_saturation: 96,
    height_cm: 178, weight_kg: 99.6, bmi: 31.4, pain_score: 6,
    // ── Labs ──
    total_cholesterol: 241, ldl: 158, hdl: 38, triglycerides: 224,
    hba1c: 7.1, glucose: 138,
    creatinine: 1.4, egfr: 52, hemoglobin: 13.2, wbc: 7.8, platelets: 224,
    // ── Problems ──
    problems: [
      { display: 'Lung cancer, primary malignant', icd10_code: 'C34.10', snomed_code: '254637007', onset_date: '2023-06-01', status: 'active', category: 'problem-list-item' },
      { display: 'Essential hypertension', icd10_code: 'I10', snomed_code: '59621000', onset_date: '2018-02-10', status: 'active', category: 'problem-list-item' },
      { display: 'Type 2 diabetes mellitus', icd10_code: 'E11.9', snomed_code: '44054006', onset_date: '2019-09-20', status: 'active', category: 'problem-list-item' },
      { display: 'Hyperlipidemia', icd10_code: 'E78.5', snomed_code: '55822004', onset_date: '2017-04-05', status: 'active', category: 'problem-list-item' },
      { display: 'Obesity', icd10_code: 'E66.9', snomed_code: '414916001', onset_date: '2016-11-12', status: 'active', category: 'problem-list-item' },
    ],
    // ── Medications ──
    medications: [
      { name: 'Metformin', rxnorm_code: '860975', dose: '1000 mg', route: 'Oral', frequency: 'Twice daily', indication: 'Type 2 DM', start_date: '2019-10-01', status: 'active' },
      { name: 'Lisinopril', rxnorm_code: '29046', dose: '10 mg', route: 'Oral', frequency: 'Once daily', indication: 'Hypertension', start_date: '2018-03-01', status: 'active' },
      { name: 'Atorvastatin', rxnorm_code: '83367', dose: '40 mg', route: 'Oral', frequency: 'Once daily at bedtime', indication: 'Hyperlipidemia', start_date: '2017-05-01', status: 'active' },
      { name: 'Carboplatin', rxnorm_code: '40048', dose: 'AUC 5 IV', route: 'Intravenous', frequency: 'Every 3 weeks', indication: 'Lung cancer', start_date: '2023-07-01', status: 'active' },
      { name: 'Aspirin', rxnorm_code: '1191', dose: '81 mg', route: 'Oral', frequency: 'Once daily', indication: 'Cardiovascular prophylaxis', start_date: '2018-03-01', status: 'active' },
    ],
    // ── Allergies ──
    allergies: [
      { substance: 'Penicillin', type: 'medication', reaction: 'Hives', severity: 'moderate', onset_date: '1995-06-01', status: 'active' },
      { substance: 'Sulfonamides', type: 'drug-class', reaction: 'Rash', severity: 'mild', onset_date: '2001-03-01', status: 'active' },
    ],
    // ── Immunizations ──
    immunizations: [
      { vaccine: 'Influenza', cvx_code: '141', date: '2023-10-15', status: 'completed', lot_number: 'FL2023-44' },
      { vaccine: 'Pneumococcal (PPSV23)', cvx_code: '33', date: '2021-05-20', status: 'completed', lot_number: null },
      { vaccine: 'COVID-19 (Moderna)', cvx_code: '207', date: '2022-01-12', status: 'completed', lot_number: 'MOD-2022-8A' },
      { vaccine: 'Shingrix (dose 2)', cvx_code: '187', date: '2022-08-04', status: 'completed', lot_number: null },
    ],
    // ── Procedures ──
    procedures: [
      { display: 'CT chest with contrast', cpt_code: '71250', snomed_code: null, date: '2023-05-28', status: 'completed', performer: 'Dr. Linda Zhao' },
      { display: 'Bronchoscopy with biopsy', cpt_code: '31625', snomed_code: null, date: '2023-06-05', status: 'completed', performer: 'Dr. Marcus Chen' },
      { display: 'Echocardiogram', cpt_code: '93306', snomed_code: null, date: '2023-08-10', status: 'completed', performer: 'Dr. Priya Patel' },
    ],
    // ── Care Team ──
    care_team: [
      { name: 'Dr. Sarah Mitchell', role: 'Primary Care Physician', npi: '1234567890', phone: '(617) 555-0200', organization: 'Mass General Hospital' },
      { name: 'Dr. Marcus Chen', role: 'Pulmonologist / Oncologist', npi: '0987654321', phone: '(617) 555-0201', organization: 'Dana-Farber Cancer Institute' },
      { name: 'Dr. Priya Patel', role: 'Cardiologist', npi: '1122334455', phone: '(617) 555-0202', organization: 'Brigham and Women\'s Hospital' },
    ],
    // ── Insurance ──
    insurance: {
      coverage_status: 'active', coverage_type: 'Medicare Part B',
      payer: 'Centers for Medicare & Medicaid Services', payer_id: 'CMS-001',
      member_id: 'MCR-142-7890', subscriber_id: 'MCR-142-7890', group_id: null,
      relationship_to_subscriber: 'self',
    },
    // ── Encounters ──
    encounters: [
      { encounter_type: 'Office Visit', date: '2024-01-08', reason: 'Oncology follow-up — lung cancer', facility: 'Dana-Farber Cancer Institute', performing_provider: 'Dr. Marcus Chen', disposition: 'Continue chemotherapy' },
      { encounter_type: 'Office Visit', date: '2023-11-14', reason: 'Diabetes management', facility: 'Mass General Hospital', performing_provider: 'Dr. Sarah Mitchell', disposition: 'Adjust metformin dose' },
    ],
    // ── Clinical Notes ──
    clinical_notes: [
      { note_type: 'progress-note', date: '2024-01-08', author: 'Dr. Marcus Chen', text: 'Patient tolerating carboplatin with mild nausea. CT shows stable 2.1cm RUL mass. Continue current regimen. Follow up in 3 weeks.' },
      { note_type: 'history-physical', date: '2023-06-10', author: 'Dr. Sarah Mitchell', text: 'Former 30 pack-year smoker, quit 2015. New diagnosis of primary NSCLC, Stage IIIA. Referred to oncology. Continue antihypertensive and statin therapy.' },
    ],
    // ── Health Status ──
    functional_status: 'ECOG 1 — Restricted in strenuous activity, ambulatory',
    mental_cognitive_status: 'Alert and oriented ×4, no cognitive impairment',
    disability_status: null,
    pregnancy_status: 'Not applicable',
    // ── SDOH ──
    sdoh_education_level: 'Some college',
    sdoh_financial_strain: 'Mild',
    sdoh_housing_status: 'Stable housing',
    sdoh_transportation_insecurity: false,
    sdoh_veteran_status: true,
    sdoh_social_isolation: 'None',
    // ── Other ──
    tobacco_status: 'former',
    assessment_plan: 'Continue carboplatin q3w. Tighten BP control — uptitrate lisinopril. HbA1c recheck in 3 months. Annual LDCT.',
    goals: ['Reduce SBP < 130 mmHg', 'HbA1c < 7.0%', 'Complete 6 cycles chemotherapy', 'Weight loss 5% body weight'],
    imaging_results: [
      { study: 'CT Chest (PET-CT)', date: '2023-12-01', finding: '2.1 cm RUL solid nodule, stable from prior. No new mediastinal adenopathy.' },
      { study: 'CXR', date: '2024-01-08', finding: 'Mild left basal atelectasis. No pleural effusion.' },
    ],
    provenance_author: 'Dr. Sarah Mitchell', provenance_organization: 'Mass General Hospital', provenance_timestamp: '2024-01-08T09:32:00Z',
  },

  {
    ptnum: 'PT-00287', label: 1, scc: 132, gender: 'f',
    first_name: 'Margaret', last_name: 'Sullivan', middle_name: 'Anne',
    date_of_birth: '1951-09-22', age: 72,
    administrative_sex: 'Female', birth_sex: 'Female', gender_identity: 'Female',
    preferred_language: 'English',
    race: 'White', ethnicity: 'Nonhispanic', tribal_affiliation: null,
    marital: 'Widowed',
    address_line: '287 Lakewood Dr', city: 'Columbus', state: 'Ohio', zip_code: '43210',
    phone: '(614) 555-0287', email: null,
    systolic_bp: 144, diastolic_bp: 88, heart_rate: 76,
    respiratory_rate: 16, temperature_c: 36.8, oxygen_saturation: 95,
    height_cm: 163, weight_kg: 73.9, bmi: 27.8, pain_score: 4,
    total_cholesterol: 228, ldl: 144, hdl: 44, triglycerides: 198,
    hba1c: 6.8, glucose: 122,
    creatinine: 1.1, egfr: 61, hemoglobin: 11.8, wbc: 6.2, platelets: 198,
    problems: [
      { display: 'Lung cancer, small cell', icd10_code: 'C34.11', snomed_code: '254637007', onset_date: '2022-11-01', status: 'active', category: 'problem-list-item' },
      { display: 'Essential hypertension', icd10_code: 'I10', snomed_code: '59621000', onset_date: '2015-06-01', status: 'active', category: 'problem-list-item' },
      { display: 'Prediabetes', icd10_code: 'R73.09', snomed_code: '15777000', onset_date: '2021-03-10', status: 'active', category: 'problem-list-item' },
      { display: 'Osteoporosis', icd10_code: 'M81.0', snomed_code: '64859006', onset_date: '2019-08-01', status: 'active', category: 'problem-list-item' },
    ],
    medications: [
      { name: 'Amlodipine', rxnorm_code: '17767', dose: '5 mg', route: 'Oral', frequency: 'Once daily', indication: 'Hypertension', start_date: '2015-07-01', status: 'active' },
      { name: 'Etoposide', rxnorm_code: '3521', dose: '100 mg/m² IV', route: 'Intravenous', frequency: 'Days 1–3 of 21-day cycle', indication: 'Small cell lung cancer', start_date: '2022-12-01', status: 'active' },
      { name: 'Alendronate', rxnorm_code: '17490', dose: '70 mg', route: 'Oral', frequency: 'Once weekly', indication: 'Osteoporosis', start_date: '2019-09-01', status: 'active' },
    ],
    allergies: [
      { substance: 'Codeine', type: 'medication', reaction: 'Nausea and vomiting', severity: 'mild', onset_date: '2010-01-01', status: 'active' },
    ],
    immunizations: [
      { vaccine: 'Influenza', cvx_code: '141', date: '2023-10-02', status: 'completed', lot_number: null },
      { vaccine: 'COVID-19 (Pfizer-BioNTech)', cvx_code: '208', date: '2021-04-18', status: 'completed', lot_number: 'PFZ-2021-5C' },
      { vaccine: 'Pneumococcal (PCV15)', cvx_code: '215', date: '2022-02-14', status: 'completed', lot_number: null },
    ],
    procedures: [
      { display: 'Low-dose CT chest', cpt_code: '71271', snomed_code: null, date: '2022-10-20', status: 'completed', performer: 'Radiology Dept' },
      { display: 'Bone density (DEXA)', cpt_code: '77080', snomed_code: null, date: '2023-04-05', status: 'completed', performer: 'Dr. Kim Lee' },
    ],
    care_team: [
      { name: 'Dr. Patricia Nguyen', role: 'Primary Care Physician', npi: '2233445566', phone: '(614) 555-0300', organization: 'OhioHealth' },
      { name: 'Dr. James Kowalski', role: 'Oncologist', npi: '3344556677', phone: '(614) 555-0301', organization: 'OSU Comprehensive Cancer Center' },
    ],
    insurance: {
      coverage_status: 'active', coverage_type: 'Medicare Advantage',
      payer: 'Humana', payer_id: 'HUM-002',
      member_id: 'HUM-287-4561', subscriber_id: 'HUM-287-4561', group_id: 'GRP-4400',
      relationship_to_subscriber: 'self',
    },
    encounters: [
      { encounter_type: 'Office Visit', date: '2024-01-15', reason: 'Oncology follow-up — SCLC', facility: 'OSU Cancer Center', performing_provider: 'Dr. James Kowalski', disposition: 'Partial response, continue etoposide' },
    ],
    clinical_notes: [
      { note_type: 'progress-note', date: '2024-01-15', author: 'Dr. James Kowalski', text: 'Cycle 3 complete. Imaging shows partial response. Patient fatigued but maintaining ADLs. BP adequate on amlodipine.' },
    ],
    functional_status: 'ECOG 2 — Ambulatory, up and about >50% of waking hours',
    mental_cognitive_status: 'Alert and oriented ×4',
    disability_status: null, pregnancy_status: 'Not applicable',
    sdoh_education_level: 'High school diploma', sdoh_financial_strain: 'Moderate',
    sdoh_housing_status: 'Stable housing', sdoh_transportation_insecurity: true,
    sdoh_veteran_status: false, sdoh_social_isolation: 'Mild',
    tobacco_status: 'former',
    assessment_plan: 'Continue etoposide-based regimen. Monitor renal function. Address transportation barriers for appointments.',
    goals: ['Complete full chemotherapy course', 'Maintain mobility and independence', 'BP < 140 mmHg'],
    imaging_results: [
      { study: 'CT Chest/Abdomen/Pelvis', date: '2024-01-10', finding: 'Partial response — primary mass reduced from 3.8 cm to 2.4 cm. No new metastatic lesions.' },
    ],
    provenance_author: 'Dr. Patricia Nguyen', provenance_organization: 'OhioHealth', provenance_timestamp: '2024-01-15T11:00:00Z',
  },

  {
    ptnum: 'PT-00458', label: 0, scc: 28, gender: 'f',
    first_name: 'Emily', last_name: 'Chen', middle_name: null,
    date_of_birth: '1979-07-04', age: 45,
    administrative_sex: 'Female', birth_sex: 'Female', gender_identity: 'Female',
    preferred_language: 'English',
    race: 'Asian', ethnicity: 'Nonhispanic', tribal_affiliation: null,
    marital: 'Married',
    address_line: '458 Sunrise Blvd', city: 'San Jose', state: 'California', zip_code: '95112',
    phone: '(408) 555-0458', email: 'emily.chen@email.com',
    systolic_bp: 118, diastolic_bp: 74, heart_rate: 68,
    respiratory_rate: 14, temperature_c: 36.6, oxygen_saturation: 99,
    height_cm: 162, weight_kg: 59.3, bmi: 22.6, pain_score: 1,
    total_cholesterol: 182, ldl: 104, hdl: 62, triglycerides: 88,
    hba1c: 5.2, glucose: 88,
    creatinine: 0.7, egfr: 98, hemoglobin: 13.4, wbc: 5.9, platelets: 248,
    problems: [
      { display: 'Seasonal allergic rhinitis', icd10_code: 'J30.1', snomed_code: '367498001', onset_date: '2005-04-01', status: 'active', category: 'problem-list-item' },
      { display: 'Vitamin D deficiency', icd10_code: 'E55.9', snomed_code: '34713006', onset_date: '2022-01-15', status: 'resolved', category: 'problem-list-item' },
    ],
    medications: [
      { name: 'Cetirizine', rxnorm_code: '20610', dose: '10 mg', route: 'Oral', frequency: 'Once daily PRN', indication: 'Allergic rhinitis', start_date: '2005-05-01', status: 'active' },
      { name: 'Cholecalciferol (Vitamin D3)', rxnorm_code: '316946', dose: '2000 IU', route: 'Oral', frequency: 'Once daily', indication: 'Vitamin D deficiency prophylaxis', start_date: '2022-02-01', status: 'active' },
    ],
    allergies: [
      { substance: 'Tree nuts', type: 'non-medication', reaction: 'Anaphylaxis', severity: 'severe', onset_date: '2000-03-01', status: 'active' },
    ],
    immunizations: [
      { vaccine: 'Influenza', cvx_code: '141', date: '2023-09-28', status: 'completed', lot_number: null },
      { vaccine: 'COVID-19 (Pfizer-BioNTech)', cvx_code: '208', date: '2021-04-05', status: 'completed', lot_number: null },
      { vaccine: 'Tdap', cvx_code: '115', date: '2020-06-12', status: 'completed', lot_number: null },
    ],
    procedures: [
      { display: 'Pap smear with HPV co-test', cpt_code: '88175', snomed_code: null, date: '2023-03-14', status: 'completed', performer: 'Dr. Rachel Kim' },
      { display: 'Mammogram screening', cpt_code: '77067', snomed_code: null, date: '2023-07-20', status: 'completed', performer: 'Radiology Dept' },
    ],
    care_team: [
      { name: 'Dr. Rachel Kim', role: 'Primary Care Physician', npi: '4455667788', phone: '(408) 555-0400', organization: 'Kaiser Permanente Santa Clara' },
    ],
    insurance: {
      coverage_status: 'active', coverage_type: 'HMO',
      payer: 'Kaiser Permanente', payer_id: 'KP-003',
      member_id: 'KP-458-3312', subscriber_id: 'KP-458-3312', group_id: 'GRP-7700',
      relationship_to_subscriber: 'self',
    },
    encounters: [
      { encounter_type: 'Preventive Visit', date: '2023-07-20', reason: 'Annual wellness exam', facility: 'Kaiser Santa Clara', performing_provider: 'Dr. Rachel Kim', disposition: 'Healthy, no changes' },
    ],
    clinical_notes: [
      { note_type: 'progress-note', date: '2023-07-20', author: 'Dr. Rachel Kim', text: 'Healthy 44yo female, annual preventive visit. All screenings up to date. Vitals normal. Continue current medications.' },
    ],
    functional_status: 'Fully independent', mental_cognitive_status: 'No concerns',
    disability_status: null, pregnancy_status: 'Not pregnant',
    sdoh_education_level: 'Graduate degree', sdoh_financial_strain: 'None',
    sdoh_housing_status: 'Stable housing', sdoh_transportation_insecurity: false,
    sdoh_veteran_status: false, sdoh_social_isolation: 'None',
    tobacco_status: null,
    assessment_plan: 'Continue preventive care. Annual mammogram and Pap smear. Seasonal allergy management.',
    goals: ['Maintain healthy weight', 'Annual preventive screenings'],
    imaging_results: [
      { study: 'Mammogram', date: '2023-07-20', finding: 'No suspicious findings. BI-RADS 1.' },
    ],
    provenance_author: 'Dr. Rachel Kim', provenance_organization: 'Kaiser Permanente', provenance_timestamp: '2023-07-20T14:20:00Z',
  },

  {
    ptnum: 'PT-00603', label: 1, scc: 161, gender: 'm',
    first_name: 'Harold', last_name: 'Washington', middle_name: 'Lee',
    date_of_birth: '1953-12-18', age: 70,
    administrative_sex: 'Male', birth_sex: 'Male', gender_identity: 'Male',
    preferred_language: 'English',
    race: 'Black', ethnicity: 'Nonhispanic', tribal_affiliation: null,
    marital: 'Divorced',
    address_line: '603 Magnolia St', city: 'Miami', state: 'Florida', zip_code: '33101',
    phone: '(305) 555-0603', email: null,
    systolic_bp: 158, diastolic_bp: 96, heart_rate: 94,
    respiratory_rate: 20, temperature_c: 37.3, oxygen_saturation: 94,
    height_cm: 176, weight_kg: 111.8, bmi: 36.1, pain_score: 8,
    total_cholesterol: 262, ldl: 181, hdl: 29, triglycerides: 312,
    hba1c: 9.1, glucose: 188,
    creatinine: 1.9, egfr: 38, hemoglobin: 11.4, wbc: 9.1, platelets: 187,
    problems: [
      { display: 'Lung cancer, adenocarcinoma', icd10_code: 'C34.12', snomed_code: '413448000', onset_date: '2023-01-15', status: 'active', category: 'problem-list-item' },
      { display: 'Type 2 diabetes mellitus with CKD', icd10_code: 'E11.65', snomed_code: '44054006', onset_date: '2012-05-01', status: 'active', category: 'problem-list-item' },
      { display: 'Chronic kidney disease, stage 3b', icd10_code: 'N18.32', snomed_code: '700379002', onset_date: '2020-08-01', status: 'active', category: 'problem-list-item' },
      { display: 'Hypertension', icd10_code: 'I10', snomed_code: '59621000', onset_date: '2008-03-01', status: 'active', category: 'problem-list-item' },
      { display: 'Severe obesity', icd10_code: 'E66.01', snomed_code: '238136002', onset_date: '2010-01-01', status: 'active', category: 'problem-list-item' },
      { display: 'Hypertriglyceridemia', icd10_code: 'E78.1', snomed_code: '302870006', onset_date: '2014-07-01', status: 'active', category: 'problem-list-item' },
    ],
    medications: [
      { name: 'Insulin glargine', rxnorm_code: '274783', dose: '30 units', route: 'Subcutaneous', frequency: 'Once daily at bedtime', indication: 'Type 2 DM', start_date: '2021-01-01', status: 'active' },
      { name: 'Insulin lispro', rxnorm_code: '86009', dose: '10 units', route: 'Subcutaneous', frequency: 'With meals', indication: 'Type 2 DM', start_date: '2021-01-01', status: 'active' },
      { name: 'Losartan', rxnorm_code: '203160', dose: '100 mg', route: 'Oral', frequency: 'Once daily', indication: 'Hypertension / CKD protection', start_date: '2020-09-01', status: 'active' },
      { name: 'Amlodipine', rxnorm_code: '17767', dose: '10 mg', route: 'Oral', frequency: 'Once daily', indication: 'Hypertension', start_date: '2020-09-01', status: 'active' },
      { name: 'Fenofibrate', rxnorm_code: '41493', dose: '145 mg', route: 'Oral', frequency: 'Once daily', indication: 'Hypertriglyceridemia', start_date: '2014-08-01', status: 'active' },
      { name: 'Pembrolizumab', rxnorm_code: '1728549', dose: '200 mg IV', route: 'Intravenous', frequency: 'Every 3 weeks', indication: 'NSCLC immunotherapy', start_date: '2023-03-01', status: 'active' },
    ],
    allergies: [
      { substance: 'Contrast dye (iodinated)', type: 'non-medication', reaction: 'Urticaria', severity: 'moderate', onset_date: '2018-06-01', status: 'active' },
      { substance: 'NSAIDs', type: 'drug-class', reaction: 'Acute kidney injury', severity: 'severe', onset_date: '2020-09-01', status: 'active' },
    ],
    immunizations: [
      { vaccine: 'Influenza (high-dose)', cvx_code: '197', date: '2023-10-10', status: 'completed', lot_number: null },
      { vaccine: 'COVID-19 (Moderna bivalent)', cvx_code: '229', date: '2022-09-20', status: 'completed', lot_number: null },
      { vaccine: 'Pneumococcal (PCV20)', cvx_code: '216', date: '2023-02-14', status: 'completed', lot_number: null },
    ],
    procedures: [
      { display: 'Hemodialysis access planning', cpt_code: '90935', snomed_code: null, date: '2023-11-01', status: 'completed', performer: 'Dr. Anita Roy' },
      { display: 'PD-L1 immunohistochemistry (biopsy)', cpt_code: '88360', snomed_code: null, date: '2023-02-01', status: 'completed', performer: 'Pathology Dept' },
    ],
    care_team: [
      { name: 'Dr. Samuel Torres', role: 'Primary Care Physician', npi: '5566778899', phone: '(305) 555-0500', organization: 'Jackson Memorial Hospital' },
      { name: 'Dr. Anita Roy', role: 'Nephrologist', npi: '6677889900', phone: '(305) 555-0501', organization: 'UHealth — University of Miami' },
      { name: 'Dr. Eric Bloom', role: 'Oncologist', npi: '7788990011', phone: '(305) 555-0502', organization: 'Sylvester Comprehensive Cancer Center' },
      { name: 'Maria Lopez RD', role: 'Registered Dietitian', npi: null, phone: '(305) 555-0503', organization: 'Jackson Memorial Hospital' },
    ],
    insurance: {
      coverage_status: 'active', coverage_type: 'Medicaid',
      payer: 'Florida Medicaid', payer_id: 'FLM-004',
      member_id: 'FLM-603-9012', subscriber_id: 'FLM-603-9012', group_id: null,
      relationship_to_subscriber: 'self',
    },
    encounters: [
      { encounter_type: 'Office Visit', date: '2024-01-20', reason: 'Oncology follow-up + CKD management', facility: 'Sylvester Cancer Center', performing_provider: 'Dr. Eric Bloom', disposition: 'Continue pembrolizumab, monitor creatinine' },
      { encounter_type: 'Office Visit', date: '2024-01-05', reason: 'Nephrology', facility: 'UHealth', performing_provider: 'Dr. Anita Roy', disposition: 'eGFR declining — discuss dialysis planning' },
    ],
    clinical_notes: [
      { note_type: 'progress-note', date: '2024-01-20', author: 'Dr. Eric Bloom', text: 'Cycle 8 pembrolizumab. Disease stable per last CT. Significant concern for CKD progression — eGFR 38. Pain 8/10, escalate analgesics with caution re: renal impairment.' },
    ],
    functional_status: 'ECOG 2', mental_cognitive_status: 'Alert, mild anxiety noted',
    disability_status: null, pregnancy_status: 'Not applicable',
    sdoh_education_level: 'High school diploma', sdoh_financial_strain: 'Severe',
    sdoh_housing_status: 'Unstable housing — temporary shelter',
    sdoh_transportation_insecurity: true, sdoh_veteran_status: false,
    sdoh_social_isolation: 'Severe',
    tobacco_status: 'former',
    assessment_plan: 'Continue pembrolizumab. Initiate dialysis planning with nephrology. Social work referral for housing and financial assistance. Pain management without NSAIDs.',
    goals: ['Stabilize renal function', 'Pain control < 4/10', 'Secure stable housing'],
    imaging_results: [
      { study: 'CT Chest/Abdomen', date: '2023-12-15', finding: 'Primary tumor stable at 3.2cm. No new lesions. Mild bilateral pleural thickening.' },
    ],
    provenance_author: 'Dr. Samuel Torres', provenance_organization: 'Jackson Memorial Hospital', provenance_timestamp: '2024-01-20T10:15:00Z',
  },

  {
    ptnum: 'PT-00714', label: 0, scc: 19, gender: 'f',
    first_name: 'Jasmine', last_name: 'Park', middle_name: null,
    date_of_birth: '1990-02-14', age: 34,
    administrative_sex: 'Female', birth_sex: 'Female', gender_identity: 'Female',
    preferred_language: 'English',
    race: 'Asian', ethnicity: 'Nonhispanic', tribal_affiliation: null,
    marital: 'Single',
    address_line: '714 Pacific Ave', city: 'Seattle', state: 'Washington', zip_code: '98101',
    phone: '(206) 555-0714', email: 'j.park@email.com',
    systolic_bp: 112, diastolic_bp: 70, heart_rate: 64,
    respiratory_rate: 14, temperature_c: 36.5, oxygen_saturation: 99,
    height_cm: 165, weight_kg: 57.9, bmi: 21.3, pain_score: 0,
    total_cholesterol: 168, ldl: 96, hdl: 58, triglycerides: 72,
    hba1c: 4.9, glucose: 82,
    creatinine: 0.6, egfr: 105, hemoglobin: 13.8, wbc: 5.1, platelets: 266,
    problems: [
      { display: 'Generalized anxiety disorder', icd10_code: 'F41.1', snomed_code: '197480006', onset_date: '2018-09-01', status: 'active', category: 'problem-list-item' },
      { display: 'Iron deficiency anemia', icd10_code: 'D50.9', snomed_code: '87522002', onset_date: '2023-02-01', status: 'resolved', category: 'problem-list-item' },
    ],
    medications: [
      { name: 'Sertraline', rxnorm_code: '36437', dose: '50 mg', route: 'Oral', frequency: 'Once daily', indication: 'Generalized anxiety disorder', start_date: '2019-01-01', status: 'active' },
      { name: 'Ferrous sulfate', rxnorm_code: '8879', dose: '325 mg', route: 'Oral', frequency: 'Once daily', indication: 'Iron deficiency', start_date: '2023-02-15', status: 'discontinued' },
    ],
    allergies: [],
    immunizations: [
      { vaccine: 'Influenza', cvx_code: '141', date: '2023-10-01', status: 'completed', lot_number: null },
      { vaccine: 'COVID-19 (Moderna)', cvx_code: '207', date: '2021-05-01', status: 'completed', lot_number: null },
      { vaccine: 'HPV (Gardasil 9)', cvx_code: '165', date: '2022-03-10', status: 'completed', lot_number: null },
    ],
    procedures: [
      { display: 'CBC with differential', cpt_code: '85025', snomed_code: null, date: '2023-02-01', status: 'completed', performer: 'Lab' },
    ],
    care_team: [
      { name: 'Dr. Amy Watkins', role: 'Primary Care Physician', npi: '8899001122', phone: '(206) 555-0700', organization: 'Virginia Mason Medical Center' },
      { name: 'Dr. Leo Fernandez', role: 'Psychiatrist', npi: '9900112233', phone: '(206) 555-0701', organization: 'UW Medicine Psychiatry' },
    ],
    insurance: {
      coverage_status: 'active', coverage_type: 'PPO',
      payer: 'Premera Blue Cross', payer_id: 'PBC-005',
      member_id: 'PBC-714-5678', subscriber_id: 'PBC-714-5678', group_id: 'GRP-TECH-2210',
      relationship_to_subscriber: 'self',
    },
    encounters: [
      { encounter_type: 'Office Visit', date: '2023-11-05', reason: 'Anxiety follow-up', facility: 'UW Medicine', performing_provider: 'Dr. Leo Fernandez', disposition: 'Continue sertraline, CBT referral' },
    ],
    clinical_notes: [
      { note_type: 'progress-note', date: '2023-11-05', author: 'Dr. Leo Fernandez', text: 'GAD well controlled on sertraline 50mg. PHQ-9 score 4. Iron deficiency resolved. Referred to CBT.' },
    ],
    functional_status: 'Fully independent', mental_cognitive_status: 'GAD, well-controlled',
    disability_status: null, pregnancy_status: 'Not pregnant',
    sdoh_education_level: 'Graduate degree', sdoh_financial_strain: 'None',
    sdoh_housing_status: 'Stable housing', sdoh_transportation_insecurity: false,
    sdoh_veteran_status: false, sdoh_social_isolation: 'None',
    tobacco_status: null,
    assessment_plan: 'Continue sertraline. CBT referral in progress. Annual preventive care.',
    goals: ['Manage anxiety symptoms', 'PHQ-7 score < 5'],
    imaging_results: [],
    provenance_author: 'Dr. Amy Watkins', provenance_organization: 'Virginia Mason Medical Center', provenance_timestamp: '2023-11-05T15:40:00Z',
  },

  {
    ptnum: 'PT-01158', label: 1, scc: 172, gender: 'm',
    first_name: 'Eugene', last_name: 'Thornton', middle_name: 'Ray',
    date_of_birth: '1949-04-30', age: 75,
    administrative_sex: 'Male', birth_sex: 'Male', gender_identity: 'Male',
    preferred_language: 'English',
    race: 'White', ethnicity: 'Nonhispanic', tribal_affiliation: null,
    marital: 'Widowed',
    address_line: '1158 Veterans Way', city: 'Detroit', state: 'Michigan', zip_code: '48201',
    phone: '(313) 555-1158', email: null,
    systolic_bp: 168, diastolic_bp: 102, heart_rate: 96,
    respiratory_rate: 22, temperature_c: 37.5, oxygen_saturation: 92,
    height_cm: 174, weight_kg: 116.2, bmi: 38.4, pain_score: 9,
    total_cholesterol: 278, ldl: 194, hdl: 26, triglycerides: 348,
    hba1c: 10.2, glucose: 214,
    creatinine: 2.4, egfr: 28, hemoglobin: 10.8, wbc: 11.2, platelets: 156,
    problems: [
      { display: 'Lung cancer, squamous cell, Stage IV', icd10_code: 'C34.90', snomed_code: '413448000', onset_date: '2022-09-01', status: 'active', category: 'problem-list-item' },
      { display: 'Type 2 diabetes mellitus, uncontrolled', icd10_code: 'E11.65', snomed_code: '44054006', onset_date: '2005-03-01', status: 'active', category: 'problem-list-item' },
      { display: 'Hypertensive heart disease', icd10_code: 'I11.9', snomed_code: '56218007', onset_date: '2010-01-01', status: 'active', category: 'problem-list-item' },
      { display: 'Chronic kidney disease, stage 4', icd10_code: 'N18.4', snomed_code: '431856006', onset_date: '2021-06-01', status: 'active', category: 'problem-list-item' },
      { display: 'Morbid obesity', icd10_code: 'E66.01', snomed_code: '238136002', onset_date: '2000-01-01', status: 'active', category: 'problem-list-item' },
      { display: 'Congestive heart failure', icd10_code: 'I50.9', snomed_code: '84114007', onset_date: '2022-03-01', status: 'active', category: 'problem-list-item' },
    ],
    medications: [
      { name: 'Insulin degludec', rxnorm_code: '1551260', dose: '50 units', route: 'Subcutaneous', frequency: 'Once daily', indication: 'T2DM', start_date: '2022-01-01', status: 'active' },
      { name: 'Furosemide', rxnorm_code: '4603', dose: '80 mg', route: 'Oral', frequency: 'Twice daily', indication: 'CHF — fluid management', start_date: '2022-04-01', status: 'active' },
      { name: 'Carvedilol', rxnorm_code: '20352', dose: '25 mg', route: 'Oral', frequency: 'Twice daily', indication: 'CHF / HTN', start_date: '2022-04-01', status: 'active' },
      { name: 'Spironolactone', rxnorm_code: '9997', dose: '25 mg', route: 'Oral', frequency: 'Once daily', indication: 'CHF', start_date: '2022-06-01', status: 'active' },
      { name: 'Docetaxel', rxnorm_code: '72962', dose: '75 mg/m² IV', route: 'Intravenous', frequency: 'Every 3 weeks', indication: 'Stage IV squamous NSCLC', start_date: '2022-11-01', status: 'active' },
    ],
    allergies: [
      { substance: 'Penicillin', type: 'medication', reaction: 'Anaphylaxis', severity: 'severe', onset_date: '1980-01-01', status: 'active' },
      { substance: 'Latex', type: 'non-medication', reaction: 'Contact dermatitis', severity: 'mild', onset_date: '2005-01-01', status: 'active' },
    ],
    immunizations: [
      { vaccine: 'Influenza (high-dose)', cvx_code: '197', date: '2023-09-15', status: 'completed', lot_number: null },
      { vaccine: 'COVID-19 (Pfizer bivalent)', cvx_code: '300', date: '2022-10-05', status: 'completed', lot_number: null },
    ],
    procedures: [
      { display: 'Right heart catheterization', cpt_code: '93451', snomed_code: null, date: '2022-03-15', status: 'completed', performer: 'Dr. Keisha Okafor' },
      { display: 'Thoracentesis', cpt_code: '32554', snomed_code: null, date: '2023-04-20', status: 'completed', performer: 'Dr. Dana Wells' },
    ],
    care_team: [
      { name: 'Dr. Dana Wells', role: 'Oncologist', npi: '1020304050', phone: '(313) 555-0600', organization: 'Karmanos Cancer Institute' },
      { name: 'Dr. Keisha Okafor', role: 'Cardiologist', npi: '2030405060', phone: '(313) 555-0601', organization: 'Henry Ford Health' },
      { name: 'Dr. Femi Adewale', role: 'Nephrologist', npi: '3040506070', phone: '(313) 555-0602', organization: 'Henry Ford Health' },
    ],
    insurance: {
      coverage_status: 'active', coverage_type: 'Medicare + VA Benefits',
      payer: 'Department of Veterans Affairs', payer_id: 'VA-006',
      member_id: 'VA-1158-ET', subscriber_id: 'VA-1158-ET', group_id: null,
      relationship_to_subscriber: 'self',
    },
    encounters: [
      { encounter_type: 'Office Visit', date: '2024-01-22', reason: 'Oncology — Stage IV NSCLC + CHF exacerbation', facility: 'Karmanos Cancer Institute', performing_provider: 'Dr. Dana Wells', disposition: 'Hold chemotherapy pending cardiac optimization' },
    ],
    clinical_notes: [
      { note_type: 'progress-note', date: '2024-01-22', author: 'Dr. Dana Wells', text: 'Significant CHF exacerbation this admission. LVEF 30%. Holding docetaxel. Goals of care discussion initiated — patient wishes to continue active treatment. Social work and palliative care consulted.' },
    ],
    functional_status: 'ECOG 3 — Limited self-care', mental_cognitive_status: 'Alert, anxious re: prognosis',
    disability_status: '100% VA disability', pregnancy_status: 'Not applicable',
    sdoh_education_level: 'Some high school', sdoh_financial_strain: 'Moderate',
    sdoh_housing_status: 'Stable housing — senior living facility',
    sdoh_transportation_insecurity: true, sdoh_veteran_status: true,
    sdoh_social_isolation: 'Moderate',
    tobacco_status: 'former',
    assessment_plan: 'Hold chemotherapy. Cardiac optimization with cardiology. Palliative care involvement. Goals of care discussion documented. VA social work referral.',
    goals: ['Symptom control — dyspnea and pain', 'Maintain quality of life', 'Goals of care alignment'],
    imaging_results: [
      { study: 'CT Chest', date: '2023-12-20', finding: 'Progressive disease — primary 4.8cm, new L3 vertebral metastasis, bilateral pleural effusions.' },
      { study: 'Echocardiogram', date: '2024-01-10', finding: 'LVEF 30%, severe systolic dysfunction, dilated LV.' },
    ],
    provenance_author: 'Dr. Dana Wells', provenance_organization: 'Karmanos Cancer Institute', provenance_timestamp: '2024-01-22T08:45:00Z',
  },

  {
    ptnum: 'PT-01261', label: 0, scc: 14, gender: 'f',
    first_name: 'Sofia', last_name: 'Martinez', middle_name: null,
    date_of_birth: '2000-08-12', age: 24,
    administrative_sex: 'Female', birth_sex: 'Female', gender_identity: 'Female',
    preferred_language: 'Spanish',
    race: 'Hispanic', ethnicity: 'Hispanic', tribal_affiliation: null,
    marital: 'Single',
    address_line: '1261 Desert Rose Ln', city: 'Tucson', state: 'Arizona', zip_code: '85701',
    phone: '(520) 555-1261', email: 'sofia.m@email.com',
    systolic_bp: 108, diastolic_bp: 68, heart_rate: 62,
    respiratory_rate: 14, temperature_c: 36.4, oxygen_saturation: 100,
    height_cm: 161, weight_kg: 53.9, bmi: 20.8, pain_score: 0,
    total_cholesterol: 162, ldl: 88, hdl: 64, triglycerides: 68,
    hba1c: 4.8, glucose: 79,
    creatinine: 0.6, egfr: 110, hemoglobin: 13.1, wbc: 5.4, platelets: 281,
    problems: [
      { display: 'Asthma, mild persistent', icd10_code: 'J45.30', snomed_code: '195967001', onset_date: '2010-06-01', status: 'active', category: 'problem-list-item' },
    ],
    medications: [
      { name: 'Albuterol inhaler', rxnorm_code: '745679', dose: '90 mcg/actuation', route: 'Inhalation', frequency: '2 puffs PRN', indication: 'Asthma — rescue inhaler', start_date: '2010-07-01', status: 'active' },
      { name: 'Fluticasone/Salmeterol (Advair)', rxnorm_code: '896209', dose: '100/50 mcg', route: 'Inhalation', frequency: 'Twice daily', indication: 'Asthma — controller', start_date: '2018-01-01', status: 'active' },
    ],
    allergies: [
      { substance: 'Aspirin', type: 'medication', reaction: 'Bronchospasm', severity: 'severe', onset_date: '2016-04-01', status: 'active' },
    ],
    immunizations: [
      { vaccine: 'Influenza', cvx_code: '141', date: '2023-10-05', status: 'completed', lot_number: null },
      { vaccine: 'COVID-19 (Moderna)', cvx_code: '207', date: '2021-06-10', status: 'completed', lot_number: null },
      { vaccine: 'HPV (Gardasil 9)', cvx_code: '165', date: '2018-05-20', status: 'completed', lot_number: null },
      { vaccine: 'Meningococcal ACWY', cvx_code: '114', date: '2018-08-01', status: 'completed', lot_number: null },
    ],
    procedures: [],
    care_team: [
      { name: 'Dr. Clara Rios', role: 'Primary Care Physician', npi: '4050607080', phone: '(520) 555-0800', organization: 'El Rio Community Health Center' },
    ],
    insurance: {
      coverage_status: 'active', coverage_type: 'Medicaid (AHCCCS)',
      payer: 'Arizona Health Care Cost Containment System', payer_id: 'AZ-007',
      member_id: 'AZ-1261-SM', subscriber_id: 'AZ-1261-SM', group_id: null,
      relationship_to_subscriber: 'self',
    },
    encounters: [
      { encounter_type: 'Office Visit', date: '2023-08-14', reason: 'Asthma follow-up', facility: 'El Rio Community Health', performing_provider: 'Dr. Clara Rios', disposition: 'Well controlled, continue current regimen' },
    ],
    clinical_notes: [
      { note_type: 'progress-note', date: '2023-08-14', author: 'Dr. Clara Rios', text: 'Asthma well controlled. Using rescue inhaler < 2x/week. Spirometry FEV1 88% predicted. Continue ICS/LABA. Advised to avoid ASA and NSAIDs.' },
    ],
    functional_status: 'Fully independent', mental_cognitive_status: 'No concerns',
    disability_status: null, pregnancy_status: 'Not pregnant',
    sdoh_education_level: 'Associate degree', sdoh_financial_strain: 'Mild',
    sdoh_housing_status: 'Stable housing', sdoh_transportation_insecurity: true,
    sdoh_veteran_status: false, sdoh_social_isolation: 'None',
    tobacco_status: null,
    assessment_plan: 'Asthma well controlled. Annual spirometry. Continue ICS/LABA. Avoid ASA/NSAIDs.',
    goals: ['Asthma symptom-free days ≥ 6/week', 'No rescue inhaler use during exercise'],
    imaging_results: [],
    provenance_author: 'Dr. Clara Rios', provenance_organization: 'El Rio Community Health Center', provenance_timestamp: '2023-08-14T10:20:00Z',
  },

  {
    ptnum: 'PT-01374', label: 0, scc: 62, gender: 'm',
    first_name: 'Terrence', last_name: 'Johnson', middle_name: 'Wayne',
    date_of_birth: '1963-05-22', age: 61,
    administrative_sex: 'Male', birth_sex: 'Male', gender_identity: 'Male',
    preferred_language: 'English',
    race: 'Black', ethnicity: 'Nonhispanic', tribal_affiliation: null,
    marital: 'Married',
    address_line: '1374 Dogwood Ct', city: 'Charlotte', state: 'North Carolina', zip_code: '28201',
    phone: '(704) 555-1374', email: 't.johnson@email.com',
    systolic_bp: 142, diastolic_bp: 88, heart_rate: 74,
    respiratory_rate: 16, temperature_c: 36.9, oxygen_saturation: 97,
    height_cm: 180, weight_kg: 104.3, bmi: 32.2, pain_score: 4,
    total_cholesterol: 222, ldl: 144, hdl: 38, triglycerides: 188,
    hba1c: 6.4, glucose: 118,
    creatinine: 1.1, egfr: 72, hemoglobin: 13.6, wbc: 7.2, platelets: 212,
    problems: [
      { display: 'Essential hypertension', icd10_code: 'I10', snomed_code: '59621000', onset_date: '2010-08-01', status: 'active', category: 'problem-list-item' },
      { display: 'Prediabetes', icd10_code: 'R73.09', snomed_code: '15777000', onset_date: '2022-05-01', status: 'active', category: 'problem-list-item' },
      { display: 'Obesity class I', icd10_code: 'E66.9', snomed_code: '414916001', onset_date: '2015-01-01', status: 'active', category: 'problem-list-item' },
      { display: 'Mixed hyperlipidemia', icd10_code: 'E78.2', snomed_code: '55822004', onset_date: '2016-03-01', status: 'active', category: 'problem-list-item' },
      { display: 'Osteoarthritis, bilateral knees', icd10_code: 'M17.11', snomed_code: '57773001', onset_date: '2020-07-01', status: 'active', category: 'problem-list-item' },
    ],
    medications: [
      { name: 'Hydrochlorothiazide', rxnorm_code: '5487', dose: '25 mg', route: 'Oral', frequency: 'Once daily', indication: 'Hypertension', start_date: '2010-09-01', status: 'active' },
      { name: 'Rosuvastatin', rxnorm_code: '301542', dose: '20 mg', route: 'Oral', frequency: 'Once daily', indication: 'Hyperlipidemia', start_date: '2016-04-01', status: 'active' },
      { name: 'Acetaminophen', rxnorm_code: '161', dose: '500 mg', route: 'Oral', frequency: 'Every 6 hours PRN', indication: 'Knee osteoarthritis pain', start_date: '2020-08-01', status: 'active' },
    ],
    allergies: [],
    immunizations: [
      { vaccine: 'Influenza', cvx_code: '141', date: '2023-10-18', status: 'completed', lot_number: null },
      { vaccine: 'COVID-19 (Pfizer)', cvx_code: '208', date: '2021-03-22', status: 'completed', lot_number: null },
      { vaccine: 'Shingrix (dose 1)', cvx_code: '187', date: '2023-06-01', status: 'completed', lot_number: null },
    ],
    procedures: [
      { display: 'Colonoscopy', cpt_code: '45378', snomed_code: null, date: '2022-11-10', status: 'completed', performer: 'Dr. Brian Lowe' },
      { display: 'Knee X-ray bilateral', cpt_code: '73562', snomed_code: null, date: '2023-03-05', status: 'completed', performer: 'Radiology Dept' },
    ],
    care_team: [
      { name: 'Dr. Angela Harris', role: 'Primary Care Physician', npi: '5060708090', phone: '(704) 555-0900', organization: 'Atrium Health' },
    ],
    insurance: {
      coverage_status: 'active', coverage_type: 'Commercial PPO',
      payer: 'BlueCross BlueShield of NC', payer_id: 'BCBS-008',
      member_id: 'BCBS-1374-TJ', subscriber_id: 'BCBS-1374-TJ', group_id: 'GRP-EMPL-4455',
      relationship_to_subscriber: 'self',
    },
    encounters: [
      { encounter_type: 'Office Visit', date: '2023-12-12', reason: 'HTN + prediabetes management', facility: 'Atrium Health', performing_provider: 'Dr. Angela Harris', disposition: 'Lifestyle intensification, recheck labs in 3 months' },
    ],
    clinical_notes: [
      { note_type: 'progress-note', date: '2023-12-12', author: 'Dr. Angela Harris', text: 'HbA1c borderline at 6.4. Weight up 3kg since last visit. Counselled on dietary changes, 150 min exercise/week. Discussed diabetes prevention program. Return 3 months for recheck.' },
    ],
    functional_status: 'Independent with mild functional limitation due to knee pain',
    mental_cognitive_status: 'No concerns',
    disability_status: null, pregnancy_status: 'Not applicable',
    sdoh_education_level: 'Bachelor\'s degree', sdoh_financial_strain: 'None',
    sdoh_housing_status: 'Stable housing', sdoh_transportation_insecurity: false,
    sdoh_veteran_status: false, sdoh_social_isolation: 'None',
    tobacco_status: null,
    assessment_plan: 'Diabetes Prevention Program referral. Intensify lifestyle modification. Recheck HbA1c and lipids in 3 months. Consider adding ACE inhibitor if BP remains >140.',
    goals: ['HbA1c < 5.7%', 'Weight loss 10 lbs', 'BP < 130/80', 'Walk 30 min/day 5 days/week'],
    imaging_results: [
      { study: 'Bilateral knee X-ray', date: '2023-03-05', finding: 'Moderate joint space narrowing medial compartments bilaterally. Osteophyte formation. No acute fracture.' },
    ],
    provenance_author: 'Dr. Angela Harris', provenance_organization: 'Atrium Health', provenance_timestamp: '2023-12-12T13:00:00Z',
  },
]
